"""empty message

Revision ID: 16bf25817800
Revises: 717f8c7308db
Create Date: 2019-04-02 11:22:14.841802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16bf25817800'
down_revision = '717f8c7308db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'])
    op.drop_column('users', 'company')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'company_id')
    # ### end Alembic commands ###
