"""empty message

Revision ID: 30090e584ec5
Revises: c64cf494e7b0
Create Date: 2019-04-08 14:54:52.581557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30090e584ec5'
down_revision = 'c64cf494e7b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test')
    # ### end Alembic commands ###
