"""empty message

Revision ID: 717f8c7308db
Revises: 08d03fbea8d7
Create Date: 2019-04-02 10:57:54.901340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '717f8c7308db'
down_revision = '08d03fbea8d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('company_city', sa.String(), nullable=False),
    sa.Column('company_address', sa.String(), nullable=True),
    sa.Column('company_revenue', sa.Float(decimal_return_scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('companies')
    # ### end Alembic commands ###
